# Render Blueprint for POS System
# This file defines the infrastructure for deploying on Render
# See: https://render.com/docs/blueprint-spec

services:
  # Backend API Service
  - type: web
    name: pos-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free  # Free tier (sleeps after 15min inactivity, 750hrs/month)
    region: oregon  # Choose your preferred region
    branch: main    # GitHub branch to deploy from
    
    # Auto-deploy on push to main branch
    autoDeploy: true
    
    # Health check endpoint
    healthCheckPath: /actuator/health
    
    # Environment variables
    envVars:
      # Database Configuration (using external Neon database)
      # Note: Set these manually in Render Dashboard
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: require
      - key: DB_POOL_SIZE
        value: 10
      - key: DB_MIN_IDLE
        value: 5
      
      # JPA Configuration
      - key: JPA_DDL_AUTO
        value: update
      - key: JPA_SHOW_SQL
        value: false
      
      # Server Configuration
      - key: SERVER_PORT
        value: 10000
      
      # JWT Configuration (REQUIRED - Add in Render Dashboard)
      - key: JWT_SECRET
        sync: false  # Must be set manually in Render dashboard
      - key: JWT_EXPIRATION
        value: 86400000
      
      # Email Configuration (REQUIRED - Add in Render Dashboard)
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false  # Must be set manually
      - key: MAIL_PASSWORD
        sync: false  # Must be set manually
      
      # Payment Gateway Configuration (Add in Render Dashboard)
      - key: RAZORPAY_API_KEY
        sync: false
      - key: RAZORPAY_API_SECRET
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      
      # CORS Configuration (Update with your frontend URL)
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend.onrender.com,http://localhost:5173
      
      # Frontend Configuration (Update with your frontend URL)
      - key: FRONTEND_RESET_URL
        value: https://your-frontend.onrender.com/auth/reset-password?token=
      
      # Logging
      - key: LOG_LEVEL_ROOT
        value: INFO
      - key: LOG_LEVEL_APP
        value: DEBUG
      - key: LOG_LEVEL_SPRING
        value: INFO
      - key: LOG_LEVEL_SECURITY
        value: INFO
      - key: LOG_LEVEL_SQL
        value: WARN
      - key: LOG_LEVEL_SQL_TRACE
        value: WARN
      - key: LOG_FILE
        value: logs/pos-system.log

# Note: Using external Neon database instead of Render's PostgreSQL
# No database service defined here - all DB credentials set via environment variables

